CREATE TABLE `leaves` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_id` int NOT NULL,
	`user_id` int NOT NULL,
	`leave_type_id` int NOT NULL,
	`unique_id` varchar(255) NOT NULL,
	`duration` varchar(255) NOT NULL,
	`leavedate` timestamp NOT NULL,
	`reason` varchar(255) NOT NULL,
	`status` enum('pending','approved','rejected') NOT NULL,
	`reject_reason` varchar(255) NOT NULL,
	`paid` enum('yes','no') NOT NULL,
	`added_by` varchar(255) NOT NULL,
	`last_updated_by` varchar(255) NOT NULL,
	`event_id` varchar(255) NOT NULL,
	`approved_by` varchar(255) NOT NULL,
	`half_day_type` enum('first_half','second_half') NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`manager_status_permission` enum('yes','no') NOT NULL,
	`approve_reason` varchar(255) NOT NULL,
	CONSTRAINT `leave_company_id_unique` UNIQUE(`company_id`),
	CONSTRAINT `leave_user_id_unique` UNIQUE(`user_id`)
);
