CREATE TABLE `attendances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_id` int NOT NULL,
	`user_id` int NOT NULL,
	`location_id` varchar(255) NOT NULL,
	`leave_id` varchar(255) NOT NULL,
	`clock_in_time` timestamp NOT NULL,
	`clock_out_time` timestamp NOT NULL,
	`clock_in_ip` varchar(255) NOT NULL,
	`clock_out_ip` varchar(255) NOT NULL,
	`working_from` varchar(255) NOT NULL,
	`late` varchar(255) NOT NULL,
	`half_day` enum('yes','no') NOT NULL,
	`added_by` varchar(255) NOT NULL,
	`last_updated_by` varchar(255) NOT NULL,
	`latitude` varchar(255) NOT NULL,
	`longitude` varchar(255) NOT NULL,
	`shift_start_time` timestamp NOT NULL,
	`shift_end_time` timestamp NOT NULL,
	`employee_shift_id` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`work_from_type` enum('office','home') NOT NULL,
	`overwrite_attendance` enum('yes','no') NOT NULL,
	`break_in_ip` varchar(255) NOT NULL,
	`break_in_time` timestamp NOT NULL,
	`break_out_ip` varchar(255) NOT NULL,
	`break_out_time` timestamp NOT NULL,
	CONSTRAINT `attendances_company_id_unique` UNIQUE(`company_id`),
	CONSTRAINT `attendances_user_id_unique` UNIQUE(`user_id`)
);
